# Generated by Django 4.2.24 on 2025-09-20 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('total_lines', models.PositiveIntegerField(default=0)),
                ('successful_imports', models.PositiveIntegerField(default=0)),
                ('failed_imports', models.PositiveIntegerField(default=0)),
                ('skip_empty_lines', models.BooleanField(default=True)),
                ('auto_assign', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Import notes or error messages')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='TextDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the document', max_length=255)),
                ('content', models.TextField(help_text='Medical text content to be annotated')),
                ('source_file', models.CharField(blank=True, help_text='Original filename if imported from file', max_length=255)),
                ('line_number', models.PositiveIntegerField(blank=True, help_text='Line number in source file', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_started', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('estimated_duration', models.DurationField(blank=True, help_text='Estimated time to complete', null=True)),
                ('actual_duration', models.DurationField(blank=True, help_text='Actual time taken', null=True)),
                ('notes', models.TextField(blank=True, help_text='Annotator notes')),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_tasks', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_task', to='annotation.textdocument')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='textdocument',
            index=models.Index(fields=['status'], name='annotation__status_bd80ba_idx'),
        ),
        migrations.AddIndex(
            model_name='textdocument',
            index=models.Index(fields=['assigned_to'], name='annotation__assigne_6f7d16_idx'),
        ),
        migrations.AddIndex(
            model_name='textdocument',
            index=models.Index(fields=['uploaded_by'], name='annotation__uploade_f9f679_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='annotationtask',
            unique_together={('document', 'annotator')},
        ),
    ]
