# Generated by Django 4.2.24 on 2025-09-20 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='textdocument',
            name='annotation__assigne_6f7d16_idx',
        ),
        migrations.AlterField(
            model_name='annotationtask',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_tasks', to='annotation.textdocument'),
        ),
        migrations.RemoveField(
            model_name='textdocument',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='textdocument',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'role': 'annotator'}, related_name='assigned_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
