# Generated by Django 4.2.24 on 2025-09-20 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0002_remove_textdocument_annotation__assigne_6f7d16_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(choices=[('manual', 'Manual Annotation'), ('llm', 'LLM Annotation'), ('hybrid', 'Hybrid Annotation')], default='llm', max_length=20)),
                ('model_used', models.CharField(blank=True, help_text='LLM model used for annotation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entities_json', models.JSONField(default=list, help_text='JSON array of extracted entities')),
                ('total_entities', models.PositiveIntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Average confidence score', null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin review notes')),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_results', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_results', to='annotation.textdocument')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'annotator'], name='annotation__documen_01e64b_idx'), models.Index(fields=['annotation_type'], name='annotation__annotat_239e0f_idx'), models.Index(fields=['model_used'], name='annotation__model_u_3c88d6_idx')],
            },
        ),
    ]
