# Generated by Django 4.2.24 on 2025-09-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_annotationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationresult',
            name='decisions_json',
            field=models.JSONField(default=dict, help_text='Track approve/reject decisions for analysis'),
        ),
        migrations.AlterField(
            model_name='annotationresult',
            name='annotation_type',
            field=models.CharField(choices=[('manual', 'Manual Annotation'), ('llm_assisted', 'LLM-Assisted Annotation'), ('llm_only', 'LLM Only (Legacy)')], default='llm_only', max_length=20),
        ),
        migrations.AlterField(
            model_name='annotationresult',
            name='entities_json',
            field=models.JSONField(default=list, help_text='JSON array of extracted entities with source/status tracking'),
        ),
        migrations.AlterField(
            model_name='annotationresult',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
