# Generated by Django 4.2.24 on 2025-09-21 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0004_annotationresult_decisions_json_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotationtask',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='annotationresult',
            name='task_type',
            field=models.CharField(choices=[('ner', 'Named Entity Recognition'), ('mcn', 'Medical Concept Normalization')], default='ner', max_length=10),
        ),
        migrations.AddField(
            model_name='annotationtask',
            name='task_type',
            field=models.CharField(choices=[('ner', 'Named Entity Recognition'), ('mcn', 'Medical Concept Normalization')], default='ner', max_length=10),
        ),
        migrations.AlterField(
            model_name='annotationresult',
            name='annotation_type',
            field=models.CharField(choices=[('manual', 'Manual Annotation'), ('llm_assisted', 'LLM-Assisted Annotation'), ('llm_only', 'LLM Only (Legacy)'), ('mcn_manual', 'MCN Manual'), ('mcn_llm_assisted', 'MCN LLM-Assisted')], default='llm_only', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='annotationtask',
            unique_together={('document', 'annotator', 'task_type')},
        ),
    ]
