# Generated by Django 4.2.24 on 2025-09-21 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0005_alter_annotationtask_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('ner', 'Named Entity Recognition'), ('mcn', 'Medical Concept Normalization'), ('all', 'All Tasks')], default='all', max_length=10)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], default='all_time', max_length=10)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('total_tasks_completed', models.PositiveIntegerField(default=0)),
                ('total_annotation_time_minutes', models.FloatField(default=0.0)),
                ('average_annotation_time_minutes', models.FloatField(default=0.0)),
                ('min_annotation_time_minutes', models.FloatField(blank=True, null=True)),
                ('max_annotation_time_minutes', models.FloatField(blank=True, null=True)),
                ('total_llm_predictions', models.PositiveIntegerField(default=0)),
                ('accepted_predictions', models.PositiveIntegerField(default=0)),
                ('modified_predictions', models.PositiveIntegerField(default=0)),
                ('rejected_predictions', models.PositiveIntegerField(default=0)),
                ('acceptance_rate', models.FloatField(default=0.0, help_text='Percentage of LLM predictions accepted without change')),
                ('modification_rate', models.FloatField(default=0.0, help_text='Percentage of LLM predictions modified')),
                ('rejection_rate', models.FloatField(default=0.0, help_text='Percentage of LLM predictions rejected')),
                ('total_edit_distance', models.PositiveIntegerField(default=0)),
                ('average_edit_distance', models.FloatField(default=0.0)),
                ('total_token_changes', models.PositiveIntegerField(default=0)),
                ('average_token_changes', models.FloatField(default=0.0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['annotator', 'task_type'], name='annotation__annotat_7ef874_idx'), models.Index(fields=['period_type', 'period_start', 'period_end'], name='annotation__period__6f7abd_idx')],
                'unique_together': {('annotator', 'task_type', 'period_type', 'period_start', 'period_end')},
            },
        ),
    ]
