# Generated by Django 4.2.24 on 2025-09-23 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0007_guideline'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('SYMPTOM', 'Symptom'), ('DISEASE', 'Disease'), ('BODY_PART', 'Body Part'), ('MEDICATION', 'Medication'), ('PROCEDURE', 'Procedure')], help_text='Type of medical entity', max_length=20, unique=True)),
                ('definition', models.TextField(help_text='Clear definition of what constitutes this entity type')),
                ('examples', models.TextField(blank=True, help_text='Examples of this entity type (optional)')),
                ('guidelines', models.TextField(blank=True, help_text='Additional annotation guidelines for this entity type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this definition is currently active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_entity_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entity_type'],
                'indexes': [models.Index(fields=['entity_type'], name='annotation__entity__ae8039_idx'), models.Index(fields=['is_active'], name='annotation__is_acti_6c9edd_idx')],
            },
        ),
    ]
