# Generated by Django 4.2.7 on 2025-10-23 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0008_entitydefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMCNMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indonesian_term', models.CharField(help_text='Original Indonesian medical term extracted from text', max_length=255)),
                ('term_context', models.TextField(blank=True, help_text='Surrounding text context where term was found')),
                ('suggested_mappings', models.JSONField(default=list, help_text='Array of suggested SNOMED-CT mappings from LLM with preferred_term_en and notes')),
                ('selected_snomed_term', models.CharField(blank=True, help_text='The SNOMED-CT preferred term selected/approved by annotator', max_length=255)),
                ('snomed_concept_id', models.CharField(blank=True, help_text='SNOMED-CT concept ID (if verified)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('modified', 'Modified')], default='pending', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score from LLM (0-1)', null=True)),
                ('mapping_notes', models.TextField(blank=True, help_text='Notes about ambiguity, cultural terms, etc from LLM')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the mapping was reviewed', null=True)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Notes from the reviewer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(blank=True, help_text='LLM model used for mapping', max_length=100)),
                ('created_by', models.ForeignKey(help_text='User who triggered the automatic MCN mapping', on_delete=django.db.models.deletion.CASCADE, related_name='created_mcn_mappings', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Document this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='auto_mcn_mappings', to='annotation.textdocument')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Annotator who reviewed this mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_mcn_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'status'], name='annotation__documen_120004_idx'), models.Index(fields=['indonesian_term'], name='annotation__indones_c87574_idx'), models.Index(fields=['status'], name='annotation__status_39fe61_idx'), models.Index(fields=['created_by'], name='annotation__created_1f25b8_idx')],
                'unique_together': {('document', 'indonesian_term')},
            },
        ),
    ]
