# Generated by Django 4.2.11 on 2025-11-10 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0009_automcnmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('openrouter', 'OpenRouter (100+ models, recommended)'), ('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude')], help_text='LLM provider name', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable provider name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Provider description and features')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is active and available')),
                ('priority', models.IntegerField(default=0, help_text='Priority order (higher = preferred), recommend OpenRouter highest')),
                ('env_var_name', models.CharField(help_text='Environment variable name (e.g., OPENROUTER_API_KEY)', max_length=100)),
                ('base_url', models.URLField(blank=True, help_text='API base URL (if applicable)')),
                ('documentation_url', models.URLField(blank=True, help_text='Link to provider documentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Provider',
                'verbose_name_plural': 'LLM Providers',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LLMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_fallback', models.BooleanField(default=True, help_text='Try other providers if preferred fails')),
                ('default_models', models.JSONField(blank=True, default=list, help_text='Default models to use in multi-LLM comparison')),
                ('enable_cost_tracking', models.BooleanField(default=True, help_text='Track API usage costs')),
                ('monthly_budget_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly API budget in USD', max_digits=10, null=True)),
                ('max_requests_per_hour', models.IntegerField(blank=True, help_text='Max requests per hour (rate limiting)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_provider', models.ForeignKey(blank=True, help_text='Preferred provider to use by default (recommend OpenRouter)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_config', to='annotation.llmprovider')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last admin who updated configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Configuration',
                'verbose_name_plural': 'LLM Configuration',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(help_text="Descriptive name for this key (e.g., 'Production Key', 'Test Key')", max_length=100)),
                ('api_key', models.CharField(help_text='API key value (stored securely)', max_length=500)),
                ('key_prefix', models.CharField(blank=True, help_text='First few characters of key for identification', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this key is currently active')),
                ('is_from_env', models.BooleanField(default=False, help_text='Whether this key comes from environment variable')),
                ('last_tested', models.DateTimeField(blank=True, help_text='Last time this key was tested', null=True)),
                ('test_status', models.CharField(blank=True, choices=[('untested', 'Not Tested'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('expired', 'Expired'), ('rate_limited', 'Rate Limited')], default='untested', help_text='Result of last test', max_length=20)),
                ('test_message', models.TextField(blank=True, help_text='Details from last test')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this key has been used')),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this key')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who added this key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='LLM provider this key belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='annotation.llmprovider')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-is_active', '-updated_at'],
                'indexes': [models.Index(fields=['provider', 'is_active'], name='annotation__provide_301aef_idx')],
            },
        ),
    ]
