# Generated by Django 4.2.11 on 2025-11-14 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0010_llmprovider_llmconfiguration_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitydefinition',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Hex color code for highlighting this entity type (e.g., #ff6b6b)', max_length=7),
        ),
        migrations.AlterField(
            model_name='entitydefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_entity_definitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
