# Generated by Django 4.2.11 on 2025-11-30 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0011_entitydefinition_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('ner', 'Named Entity Recognition'), ('mcn', 'Medical Concept Normalization')], default='ner', help_text='Type of annotation task', max_length=10)),
                ('entities_json', models.JSONField(default=list, help_text='JSON array of expert-validated entities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validation_notes', models.TextField(blank=True, help_text='Notes about validation process and decisions')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this gold standard is currently active')),
                ('created_by', models.ForeignKey(help_text='Expert who created this gold standard', on_delete=django.db.models.deletion.CASCADE, related_name='created_gold_standards', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Document with gold standard annotation', on_delete=django.db.models.deletion.CASCADE, related_name='gold_standards', to='annotation.textdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotatorAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('ner', 'Named Entity Recognition'), ('mcn', 'Medical Concept Normalization')], default='ner', help_text='Type of annotation task', max_length=10)),
                ('cohens_kappa', models.FloatField(blank=True, help_text="Cohen's kappa coefficient (-1 to 1)", null=True)),
                ('percent_agreement', models.FloatField(blank=True, help_text='Simple percentage agreement (0-100)', null=True)),
                ('total_entities_annotator1', models.PositiveIntegerField(default=0, help_text='Total entities marked by annotator 1')),
                ('total_entities_annotator2', models.PositiveIntegerField(default=0, help_text='Total entities marked by annotator 2')),
                ('agreed_entities', models.PositiveIntegerField(default=0, help_text='Number of entities both annotators agreed on')),
                ('disagreed_entities', models.PositiveIntegerField(default=0, help_text='Number of entities annotators disagreed on')),
                ('agreement_details_json', models.JSONField(default=dict, help_text='Detailed breakdown of agreements/disagreements by entity type')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this agreement calculation')),
                ('annotator1', models.ForeignKey(help_text='First annotator', on_delete=django.db.models.deletion.CASCADE, related_name='agreements_as_annotator1', to=settings.AUTH_USER_MODEL)),
                ('annotator2', models.ForeignKey(help_text='Second annotator', on_delete=django.db.models.deletion.CASCADE, related_name='agreements_as_annotator2', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Document that was annotated by multiple annotators', on_delete=django.db.models.deletion.CASCADE, related_name='annotator_agreements', to='annotation.textdocument')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.FloatField(blank=True, help_text='Precision score (0-1)', null=True)),
                ('recall', models.FloatField(blank=True, help_text='Recall score (0-1)', null=True)),
                ('f1_score', models.FloatField(blank=True, help_text='F1 score (0-1)', null=True)),
                ('true_positives', models.PositiveIntegerField(default=0, help_text='Correctly identified entities')),
                ('false_positives', models.PositiveIntegerField(default=0, help_text='Incorrectly identified entities')),
                ('false_negatives', models.PositiveIntegerField(default=0, help_text='Missed entities')),
                ('true_negatives', models.PositiveIntegerField(default=0, help_text='Correctly identified non-entities')),
                ('annotation_time_seconds', models.FloatField(blank=True, help_text='Total time spent on annotation', null=True)),
                ('average_time_per_entity', models.FloatField(blank=True, help_text='Average time per entity in seconds', null=True)),
                ('metrics_by_entity_type', models.JSONField(default=dict, help_text='Precision/recall/F1 breakdown by entity type')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional evaluation notes')),
                ('annotation_result', models.ForeignKey(help_text='Annotation result being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='annotation.annotationresult')),
                ('gold_standard', models.ForeignKey(blank=True, help_text='Gold standard used for evaluation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_metrics', to='annotation.goldstandard')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='goldstandard',
            index=models.Index(fields=['document', 'task_type'], name='annotation__documen_b52589_idx'),
        ),
        migrations.AddIndex(
            model_name='goldstandard',
            index=models.Index(fields=['is_active'], name='annotation__is_acti_049b9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goldstandard',
            unique_together={('document', 'task_type')},
        ),
        migrations.AddIndex(
            model_name='annotatoragreement',
            index=models.Index(fields=['document', 'task_type'], name='annotation__documen_11a4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='annotatoragreement',
            index=models.Index(fields=['annotator1', 'annotator2'], name='annotation__annotat_a21b51_idx'),
        ),
        migrations.AddIndex(
            model_name='annotatoragreement',
            index=models.Index(fields=['cohens_kappa'], name='annotation__cohens__cac3f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='annotatoragreement',
            unique_together={('document', 'annotator1', 'annotator2', 'task_type')},
        ),
        migrations.AddIndex(
            model_name='annotationmetrics',
            index=models.Index(fields=['annotation_result'], name='annotation__annotat_7cf105_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationmetrics',
            index=models.Index(fields=['gold_standard'], name='annotation__gold_st_36c182_idx'),
        ),
        migrations.AddIndex(
            model_name='annotationmetrics',
            index=models.Index(fields=['f1_score'], name='annotation__f1_scor_225905_idx'),
        ),
    ]
