# Generated by Django 4.2.24 on 2025-09-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annotation_mode',
            field=models.CharField(choices=[('manual_only', 'Manual Annotation Only'), ('llm_assisted_only', 'LLM-Assisted Annotation Only'), ('both', 'Both Manual and LLM-Assisted')], default='both', help_text='Determines which annotation methods this annotator can use', max_length=20),
        ),
    ]
