# Generated by Django 4.2.11 on 2025-10-28 09:36

from django.db import migrations


def update_annotation_mode_to_manual_only(apps, schema_editor):
    """Update all users with annotation_mode='both' to 'manual_only'"""
    User = apps.get_model('authentication', 'User')
    User.objects.filter(annotation_mode='both').update(annotation_mode='manual_only')


def reverse_update_annotation_mode(apps, schema_editor):
    """Reverse migration - restore to 'both'"""
    User = apps.get_model('authentication', 'User')
    User.objects.filter(annotation_mode='manual_only').update(annotation_mode='both')


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_annotation_mode'),
    ]

    operations = [
        migrations.RunPython(
            update_annotation_mode_to_manual_only,
            reverse_code=reverse_update_annotation_mode
        ),
    ]
