# Generated by Django 4.2.11 on 2025-11-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_update_annotation_mode_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='annotation_mode',
            field=models.CharField(choices=[('manual_only', 'Manual Annotation Only'), ('llm_assisted_only', 'LLM-Assisted Annotation Only'), ('both', 'Both Manual and LLM-Assisted')], default='manual_only', help_text='Determines which annotation methods this annotator can use', max_length=20),
        ),
    ]
