# Generated by Django 4.2.24 on 2025-12-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_annotation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('annotator', 'Annotator'), ('expert', 'Expert Annotator')], default='annotator', help_text='User role determines access permissions', max_length=20),
        ),
    ]
