# Generated by Django 4.2.27 on 2026-01-11 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier for the achievement', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('description', models.TextField(help_text='How to earn this achievement')),
                ('icon', models.CharField(default='🏅', help_text='Emoji icon', max_length=10)),
                ('points_reward', models.PositiveIntegerField(default=0, help_text='Bonus points when earned')),
                ('difficulty', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('required_annotations', models.PositiveIntegerField(blank=True, null=True)),
                ('required_entities', models.PositiveIntegerField(blank=True, null=True)),
                ('required_streak', models.PositiveIntegerField(blank=True, null=True)),
                ('required_ner_count', models.PositiveIntegerField(blank=True, null=True)),
                ('required_mcn_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_secret', models.BooleanField(default=False, help_text='Hidden until earned')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'difficulty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Additional context about earning')),
                ('is_notified', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earners', to='authentication.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ner_complete', 'NER Annotation Completed'), ('mcn_complete', 'MCN Annotation Completed'), ('streak_bonus', 'Streak Bonus'), ('speed_bonus', 'Speed Bonus'), ('quality_bonus', 'Quality Bonus'), ('first_of_day', 'First Annotation of Day'), ('achievement', 'Achievement Bonus'), ('level_up', 'Level Up Bonus'), ('manual_adjustment', 'Manual Adjustment')], max_length=30)),
                ('points', models.IntegerField(help_text='Points added (positive) or removed (negative)')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('annotation_id', models.PositiveIntegerField(blank=True, null=True)),
                ('achievement_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0, help_text='All-time total points')),
                ('weekly_points', models.PositiveIntegerField(default=0, help_text='Points this week (resets Monday)')),
                ('weekly_reset_date', models.DateField(blank=True, help_text='Date of last weekly reset', null=True)),
                ('level', models.PositiveIntegerField(default=1, help_text='Current level (1-8)')),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Current consecutive days')),
                ('longest_streak', models.PositiveIntegerField(default=0, help_text='Best streak ever')),
                ('last_annotation_date', models.DateField(blank=True, help_text='Date of last annotation', null=True)),
                ('total_annotations', models.PositiveIntegerField(default=0, help_text='Total annotations completed')),
                ('total_entities', models.PositiveIntegerField(default=0, help_text='Total entities annotated')),
                ('ner_annotations', models.PositiveIntegerField(default=0, help_text='NER annotations completed')),
                ('mcn_annotations', models.PositiveIntegerField(default=0, help_text='MCN annotations completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points'],
            },
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['code'], name='authenticat_code_bbba54_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['is_active'], name='authenticat_is_acti_443581_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'earned_at'], name='authenticat_user_id_f81a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['is_notified'], name='authenticat_is_noti_01e459_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['user', '-created_at'], name='authenticat_user_id_1ff09c_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['action_type'], name='authenticat_action__0cdc4e_idx'),
        ),
        migrations.AddIndex(
            model_name='annotatorprofile',
            index=models.Index(fields=['-total_points'], name='authenticat_total_p_3ae032_idx'),
        ),
        migrations.AddIndex(
            model_name='annotatorprofile',
            index=models.Index(fields=['-weekly_points'], name='authenticat_weekly__5e554f_idx'),
        ),
        migrations.AddIndex(
            model_name='annotatorprofile',
            index=models.Index(fields=['level'], name='authenticat_level_0a1bf5_idx'),
        ),
    ]
