# Generated by Django 4.2.27 on 2026-02-07 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_gamification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_ner_complete', models.PositiveIntegerField(default=10, help_text='Points for completing an NER annotation')),
                ('points_mcn_complete', models.PositiveIntegerField(default=15, help_text='Points for completing an MCN annotation')),
                ('points_first_of_day', models.PositiveIntegerField(default=5, help_text='Bonus for first annotation of the day')),
                ('points_speed_bonus', models.PositiveIntegerField(default=3, help_text='Bonus for fast completion')),
                ('points_quality_bonus', models.PositiveIntegerField(default=2, help_text='Bonus for high confidence')),
                ('points_streak_per_day', models.PositiveIntegerField(default=1, help_text='Streak bonus per consecutive day')),
                ('points_streak_max', models.PositiveIntegerField(default=7, help_text='Maximum streak bonus')),
                ('points_level_up', models.PositiveIntegerField(default=10, help_text='Bonus points on level up')),
                ('speed_threshold_ner', models.PositiveIntegerField(default=180, help_text='Seconds under which NER earns speed bonus')),
                ('speed_threshold_mcn', models.PositiveIntegerField(default=300, help_text='Seconds under which MCN earns speed bonus')),
                ('quality_threshold', models.FloatField(default=0.9, help_text='Confidence above which quality bonus is earned (0-1)')),
                ('streak_enabled', models.BooleanField(default=True, help_text='Enable streak tracking and bonus')),
                ('speed_bonus_enabled', models.BooleanField(default=True, help_text='Enable speed bonus')),
                ('quality_bonus_enabled', models.BooleanField(default=True, help_text='Enable quality bonus')),
                ('first_of_day_enabled', models.BooleanField(default=True, help_text='Enable first-of-day bonus')),
                ('leaderboard_enabled', models.BooleanField(default=True, help_text='Enable leaderboard')),
                ('level_definitions', models.JSONField(blank=True, default=list, help_text='Level definitions as [[level, title, threshold], ...]')),
                ('weekly_reset_day', models.PositiveIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, help_text='Day of week for weekly points reset (0=Monday)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gamification_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gamification Configuration',
                'verbose_name_plural': 'Gamification Configuration',
            },
        ),
    ]
