# Generated by Django 4.2.27 on 2026-02-07 17:48

from django.db import migrations


DEFAULT_LEVELS = [
    [1, 'Novice Annotator', 0],
    [2, 'Junior Annotator', 50],
    [3, 'Annotator', 150],
    [4, 'Senior Annotator', 400],
    [5, 'Expert Annotator', 800],
    [6, 'Master Annotator', 1500],
    [7, 'Grand Master', 3000],
    [8, 'Annotation Legend', 5000],
]


def create_default_config(apps, schema_editor):
    GamificationConfig = apps.get_model('authentication', 'GamificationConfig')
    if not GamificationConfig.objects.filter(pk=1).exists():
        GamificationConfig.objects.create(
            pk=1,
            level_definitions=DEFAULT_LEVELS,
        )


def reverse_default_config(apps, schema_editor):
    GamificationConfig = apps.get_model('authentication', 'GamificationConfig')
    GamificationConfig.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_gamification_config'),
    ]

    operations = [
        migrations.RunPython(create_default_config, reverse_default_config),
    ]
